### ISSUE TITLE
Backgroud loading of COLLADA files

### ISSUE THREAD

**Issue by crobi** [rmx/threejs-collada#1]
Loading of big COLLADA files can be slow and freeze the browser tab. Ideas of improving the speed and/or responsiveness:
## Web workers
- True background execution
- Messages passed to and from web workers are passed by value. Meshes would have to be serialized and deserialized to get them out of the web worker.
- ArrayBuffers can be transferred by reference (destructive assignment, no copy involved). Currently only Chrome supports this. See "web workers transferable objects"
## Web workers with proxies
- In a web worker, parse the COLLADA file and create simple proxy objects that contain pre-processed geometry data in typed arrays.
- Transfer proxy objects to the main thread (try using the fast chrome transfer of typed arrays, if possible).
- In the main thread, create three.js objects from the proxy objects. This part unfortunately cannot be executed in the background.
## Settimeout
- Call all parsing functions asynchronously with a small delay
- Browsers enforce a minimum delay of 2-10ms
- No background execution, just better responsiveness
## postMessage
- enqueue all method calls in a custom queue and use window.postMessage to execute the next call in the queue
- No background execution, just better responsiveness

**Comment by wereHamster** [comment]
FYI: web browsers enforce a minimum timeout that is >0. See https://developer.mozilla.org/en/DOM/window.setTimeout#Minimum_delay_and_timeout_nesting

**Comment by crobi** [comment]
Right, replace settimeout by window.postMessage(that was what I was looking for, anyway)

**Comment by crobi** [comment]
COLLADA is just not a suitable asset format. Giving up on improving the performance.
