### ISSUE TITLE
Convert to json for three.js

### ISSUE THREAD

**Issue by ghost** [rmx/threejs-collada#15]
Hi, is there a plane to convert collada to json for three.js

**Comment by crobi** [comment]
This is a repository for the COLLADA loader only. Please see the three.js project for support on JSON files.

To convert collada to three.js json files, you can use [Blender](http://www.blender.org/) to load the file and then the three.js [json export plugin](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender) to save a json file.

**Comment by ghost** [comment]
Thanks, @crobi ! I have a question about Collada. How can calculate each bone's pos, rot and scl at every keyframe.
