### ISSUE TITLE
some collada files are displayed incorrectly in webgl

### ISSUE THREAD

**Issue by bcohen** [rmx/threejs-collada#16]
First of all, thank you very much for this tool. The robotics community really appreciates it :). 

I came across this collada parser as part of the http://robotwebtools.org/ project and most of the time, it works great. However we do see sometimes that, some collada files get loaded incorrectly. By that I mean, some textures aren't loaded at all, some textures look bad and some of the "parts" of the drawing are missing altogether. Some other folks that use the robot web tools have experienced the same thing....in general, the community has been using [this tool](http://n.ethz.ch/~crobi/threejs-collada/view.html) to see which dae files load well and which ones don't - and then  chooses meshes for their projects this way.

We were wondering whether anyone knows why this happens? Maybe there is some way we can preprocess our meshes to prevent it? Is this related to how some submeshes are described in the file? Any advice or clues would be appreciated.

For example, we downloaded and modified [this kitchen](http://sketchup.google.com/3dwarehouse/details?mid=189f76cce9fc10a6f6f89f7c1ba65452&prevstart=48) from 3dwarehouse (we removed the ceiling and some other parts). The modified version is hosted [here](http://pr2base.grasp.upenn.edu:85/tar/kitchen-bcohen.zip) in dae, stl, skp format.

The kitchen:
![kitchen](https://f.cloud.github.com/assets/238012/963472/aacdb7a6-0503-11e3-837a-27358a5571f7.png)

The kitchen visualized with webgl (same result would be found using [this tool](http://n.ethz.ch/~crobi/threejs-collada/view.html)):
![kitchen_in_webgl](https://f.cloud.github.com/assets/238012/963473/b0a9537e-0503-11e3-9ac0-904a652dbe86.png)

(Thank you very much in advance)

**Comment by crobi** [comment]
Parts that are missing alltogether: your file uses `<library_nodes>`, which is not supported yet by the loader - I didn't expect this feature to be used. I'll open a separate issue for this (#17).

Materials looking "bad": I'll need to investigate this in detail. Do you have specific examples (in the file you posted)? One thing I see is the floor texture is rendered with "clamp" instead of "repeat" texture addressing mode. Not sure if this a problem with the COLLADA format, the sketchup exporter, your specific file, or this loader.
Possibly related: https://github.com/mrdoob/three.js/issues/2569

**Comment by bcohen** [comment]
Thanks for the quick response.

Ahhh OK. I just grepped for "library_nodes" in my folder of meshes and almost all of the dae files that I pulled off of 3dwarehouse came up. This makes sense now. Thanks.

Materials looking bad: Yea, I was referring to the floor texture. I'll ask my teammates for more examples.

**Comment by bcohen** [comment]
My team is curious if there are plans to work on issue #17 in the near future?  I'm asking because we are wondering if we should look into ways of getting around this by either searching for another parser, converting dae files with library_nodes to ones without or figuring out how to add the functionality to this parser.

Thanks again!

**Comment by crobi** [comment]
I had a quick look at how difficult #17 would be to implement. It's doable, but a proper implementation would take more time than I have in the near future. Please see the corresponding issue for details.

As much as I'd love to see this loader being used, here's a couple of thoughts:
- COLLADA is a very complex format for content exchange between modelling tools and generally not suitable as a runtime format.
- In addition to its complexity, the COLLADA specification is not very precise and every modelling tool uses a different subset of the format. I don't expect it will work flawlessly across different tools any time soon.
- While this loader seems to work better than the built-in three.js COLLADA loader, there will always be bugs and features not implemented, and I won't always be able to provide proffessional support.
- COLLADA as a runtime format is therefore good for rapid prototyping, but if you use it for assets of a commercial grade application, I would consider using the native three.js json format (exporters for blender and 3ds max available) or [glTF](https://github.com/KhronosGroup/glTF).
- These runtime formats are usually slightly smaller and load orders of magnitude faster than COLLADA.
- The disadvantage of these runtime formats is that they add additional tools to your toolchain, and thus more work for your users.

**Comment by crobi** [comment]
About the texture repeat problem: WebGL only supports the `repeat` wrapping mode for power-of-two textures. Your ground texture is 401x401. You'll need to resize it to 256x256 or 512x512 to get the desired effect. Three.js silently overrides the wrapping mode to `clamp to edge` if the texture is not power-of-two.

**Comment by bcohen** [comment]
Thanks a lot for the quick and detailed response. 

couple of thoughts:
We are sad to hear it but understand completely. I don't have an opinion on the COLLADA file format being used at runtime....on my project, we just load them in at startup and that's it for the session....it may not be optimal but it's been working. Sadly, our community relies heavily on COLLADA files so I think we will need to find another solution. If you hear of anything, please post it here :). We will look into the json format or gitf formats out there too.

texture repeat problem:
Thanks a lot for the insight. This is a very doable fix for us.

thanks again. :+1:

**Comment by bcohen** [comment]
For people who are using collada files created in SketchUp:

If you want to get around this issue ("library nodes" are ignored), then just ungroup all of the components of your mesh before exporting to Collada. From recent experience, it seems like if all of the components are completely ungrouped - then no "library nodes" are created. Highlight everything, click ungroup and export to collada.....now it should the file should be loaded correctly by this loader.

**Comment by crobi** [comment]
The soruce of the problems described here is discussed in #17
