### ISSUE TITLE
Can't load skeleton animation files from Cheetah3D

### ISSUE THREAD

**Issue by noseglid** [rmx/threejs-collada#19]
For some reason it is not possible to load collada files exported from Cheetah3D. It claims that it cannot find the skeleton for a skinned mesh:

ColladaLoader2 ERROR: Controller instance for a skinned mesh has no skeleton, mesh ignored

Sample file is uploaded to: http://noseglid.github.io/chump.dae 

This may very well be an issue with the Collada export for Cheetah3D. I'll check on both ends.

**Comment by crobi** [comment]
The `<instance_controller>` element is missing a `<skeleton>` element in your file.

The spec is not 100% clear on this, but from my interpretation, this is is a problem with the COLLADA file. The `<skeleton>` element is optional, but the spec does not say what to do if it's missing and it implies that it can only be missing for morph controllers. 

You can load your file by manually replacing

```
<instance_controller url="#ID24231968Controller"/>
```

by

```
<instance_controller url="#ID24231968Controller">
    <skeleton>#ID24192192</skeleton>
</instance_controller>
```

Finally, a word of warning: I am working on a major rewrite of the loader that will completely change its API. I will probably create a new repository for it, so I won't fix this issue in this loader.

**Comment by noseglid** [comment]
I see. I'll check with the devs of Cheetah3D what their take on this is. It appears as the bundled Collada loader of three.js have the same issue.

Thanks for your help!
