### ISSUE TITLE
Improve the loader performance

### ISSUE THREAD

**Issue by crobi** [rmx/threejs-collada#2]
Profile for loading an 800K face mesh (dragon). Almost 50% of the time spent in the garbage collector....

<table border="0" cellpadding="0" cellspacing="0" width="479" style="border-collapse:
 collapse;table-layout:fixed;width:359pt">
 <colgroup><col width="351" style="mso-width-source:userset;mso-width-alt:12836;width:263pt">
 <col class="xl72" width="64" span="2" style="width:48pt">
 </colgroup><tbody><tr height="20" style="height:15.0pt">
  <td height="20" width="351" style="height:15.0pt;width:263pt">(garbage collector)</td>
  <td class="xl72" align="right" width="64" style="width:48pt">2737.95</td>
  <td class="xl72" align="right" width="64" style="width:48pt">2737.95</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">onFileLoaded</td>
  <td class="xl72" align="right">1632.97</td>
  <td class="xl72" align="right">6015.88</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._strToInts</td>
  <td class="xl72" align="right">1020.98</td>
  <td class="xl72" align="right">1774.96</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._strToFloats</td>
  <td class="xl72" align="right">764.98</td>
  <td class="xl72" align="right">1482.97</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._addEmptyUVs</td>
  <td class="xl72" align="right">250.00</td>
  <td class="xl72" align="right">255.99</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._addTrianglesToGeometry</td>
  <td class="xl72" align="right">170.00</td>
  <td class="xl72" align="right">744.99</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">(program)</td>
  <td class="xl72" align="right">164.00</td>
  <td class="xl72" align="right">164.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._floatsToVec3</td>
  <td class="xl72" align="right">122.00</td>
  <td class="xl72" align="right">128.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._createVector3Array</td>
  <td class="xl72" align="right">112.00</td>
  <td class="xl72" align="right">241.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Geometry.computeCentroids</td>
  <td class="xl72" align="right">102.00</td>
  <td class="xl72" align="right">102.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Geometry.computeFaceNormals</td>
  <td class="xl72" align="right">87.00</td>
  <td class="xl72" align="right">115.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Face3</td>
  <td class="xl72" align="right">76.00</td>
  <td class="xl72" align="right">76.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseSourceChild</td>
  <td class="xl72" align="right">62.00</td>
  <td class="xl72" align="right">1544.97</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseTrianglesChild</td>
  <td class="xl72" align="right">60.00</td>
  <td class="xl72" align="right">1834.96</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Vector3.isZero</td>
  <td class="xl72" align="right">24.00</td>
  <td class="xl72" align="right">24.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Geometry.computeBoundingBox</td>
  <td class="xl72" align="right">11.00</td>
  <td class="xl72" align="right">11.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Geometry.computeBoundingSphere</td>
  <td class="xl72" align="right">10.00</td>
  <td class="xl72" align="right">17.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Vector3.length</td>
  <td class="xl72" align="right">7.00</td>
  <td class="xl72" align="right">7.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._createGeometry</td>
  <td class="xl72" align="right">6.00</td>
  <td class="xl72" align="right">978.98</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._applyUpConversion</td>
  <td class="xl72" align="right">6.00</td>
  <td class="xl72" align="right">6.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._strToInts</td>
  <td class="xl72" align="right">5.00</td>
  <td class="xl72" align="right">5.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Vector3.copy</td>
  <td class="xl72" align="right">4.00</td>
  <td class="xl72" align="right">4.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._strToInts</td>
  <td class="xl72" align="right">2.00</td>
  <td class="xl72" align="right">2.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">logMessage</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">logMessage</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseColladaChild</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">3382.93</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseSceneNode</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._createMesh</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">996.98</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Vector3.clone</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">setLineBuffers</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">(anonymous function)</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Geometry.computeFaceNormals</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Vector3.copy</td>
  <td class="xl72" align="right">1.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">(root)</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">8919.82</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">logActionEnd</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">logActionStart</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2.parse</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">4380.91</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseXml</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">3382.93</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseLibGeometryChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">3380.93</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseGeometryChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">3380.93</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseMeshChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">3380.93</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseSource</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1544.97</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseVertices</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseVerticesChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseInput</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseTriangles</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1834.96</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseLibVisualSceneChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._parseVisualSceneChild</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">1.00</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._createSceneGraph</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">996.98</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">ColladaLoader2._createSceneGraphNode</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">996.98</td>
 </tr>
 <tr height="20" style="height:15.0pt">
  <td height="20" style="height:15.0pt">THREE.Mesh</td>
  <td class="xl72" align="right">0.00</td>
  <td class="xl72" align="right">17.00</td>
 </tr>
 
 <tr height="0" style="display:none">
  <td width="351" style="width:263pt"></td>
  <td width="64" style="width:48pt"></td>
  <td width="64" style="width:48pt"></td>
 </tr>
 
</tbody></table>

**Comment by wereHamster** [comment]
A lot of time is being spent parsing the strings, even though the actual values may not be used. And the parsing generates a lot of garbage (_strToStrings in particular). Wouldn't it be better to parse the data lazily, only when needed?

**Comment by wereHamster** [comment]
Something like a388d7483. But extended to all the nodes, not just &lt;source&gt;.

**Comment by crobi** [comment]
If any data from the collada file is not used, it shouldn't even be in there. Well formatted collada files will use all of the arrays. So I'd rather parse the string immediately (not sure how to do this without garbage) than hold on to the (huge) strings for a long time. I'd expect a few huge typed arrays should not be too much overhead fr the garbage collector

**Comment by crobi** [comment]
I don't think it's possible to efficiently load COLLADA in javascript. It's about the worst asset format there is. Giving up on this.
