### ISSUE TITLE
Collada loading with colladaLoader2.js

### ISSUE THREAD

**Issue by olivierhuntemann** [rmx/threejs-collada#4]
Hi,

I try to implement your loader, but i don't understand :

This is my code with colladaLoader.js :

```
objloader = new THREE.ColladaLoader();
objloader.load(dae, function colladaReady(collada) {
    element = collada.scene;
    THREE.SceneUtils.traverseHierarchy(element, function(node) {
        node.material = material;
    });
});
```

What is the code with ColladaLoader2.js to make same thing ?

Thanks in advance

**Comment by wereHamster** [comment]
Compile ColladaLoader2.coffee into javascript, include it in your webpage and then use:

```
objloader = new ColladaLoader2();
```

**Comment by crobi** [comment]
As there has been no response for several month, I assume this issue is resolved.
