### ISSUE TITLE
Closure compiler

### ISSUE THREAD

**Issue by crobi** [rmx/threejs-collada#9]
Try compiling the code using googles closure compiler. All threejs functions have to be [declared as externs](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs).

**Comment by Goutte** [comment]
Looks interesting.
I'll look forward to some project configuration for compiling both coffee and three.

Good luck !

**Comment by crobi** [comment]
I have added [a very incomplete file](https://github.com/crobi/ColladaAnimationCompress/blob/master/threejs-exports.js) that contains threejs exports. It can be used to compile the collada loader using the closure compiler without errors.

I use the closure compiler mainly for error checking. For now, use the [closure compiler UI](http://closure-compiler.appspot.com/home) and paste the contents of above file into the UI, followed by the javascript version of the collada loader to run it against the compiler.

**Comment by crobi** [comment]
The project now compiles with the closure compiler. The compiled code works and there are (almost) no warnings. The code also includes strong type annotations and is 95% typed (according to closure).
